### ISSUE TITLE
Unbound SSL_Log

### ISSUE THREAD

**Issue by SinghSek** [fkie-cad/friTap#40]
When running Fritap to capture TLS traffic and keys on a rooted android device via ADB, I encounter an issue stating that SSL_Log cannot be accessed where it is a local variable.

The command I used is 'fritap -m -p log.pcap --full_capture -k keys.log 10967' where the number is the PID. 

Below is the output from the command line: 
[-] Invalid Argument passed to Frida: device not found

(In Frida file)
frida.InvalidArgumentError: device not found

During handling of the above exception, another exception occurred:

(In Fritap File):
line 189, in main
    ssl_log.pcap_cleanup(parsed.full_capture,parsed.mobile,parsed.pcap)
    ^^^^^^^
UnboundLocalError: cannot access local variable 'ssl_log' where it is not associated with a value

I am running a miniconda environment in VSCode, but have also tried pycharm with the same problem. Frida and FriTap are both installed and the PID was found prior using 'frida-ps -U | findstr euicc'

**Comment by monkeywave** [comment]
Hi @SinghSek,

Thank you for reporting this issue :-) 

Could you please provide us with a bit more information to help us debug this further?

1. Which version of friTap are you using? The latest version is **1.2.8.0**. If you're not on the latest version, please try updating and see if the issue persists.
2. Could you run friTap with the `-do` and `-v` parameters for more detailed debugging output and share the results? For example:
   ```bash
   fritap -m -p log.pcap --full_capture -k keys.log -do -v 10967
   ```

For reference, I’ve tested this setup using both a Google Pixel 5 (rooted) and an Android Virtual Device (AVD), and everything works as expected without any issues. It seems like the problem may be related to either the device connection or environment configuration.

Looking forward to your feedback, and thanks for helping us improve friTap!

All the best

Daniel

**Comment by SinghSek** [comment]
I'm on both the latest version of Fritap and Frida-tools/server on my pc and on the android devices. I ran the commands connected to both an S21 running android 11 rooted with Magisk, and a Pixel 9 running android 15 rooted with magisk. On the S21 I directly pushed the frida-server file and run it off the adb shell, while the pixel 9 has frida-server running as a magisk module. 

When running the code as asked, the following occurs: 

Start logging
Press Ctrl+C to stop logging

[-] Invalid Argument passed to Frida: device not found
Traceback (most recent call last):
  File "C:\Users\Jared\miniconda3\envs\FriTap\Lib\site-packages\friTap\friTap.py", line 115, in main
    ssl_log = SSL_Logger(parsed.exec, parsed.pcap, parsed.verbose,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jared\miniconda3\envs\FriTap\Lib\site-packages\friTap\ssl_logger.py", line 77, in __init__
    self.init_fritap()
  File "C:\Users\Jared\miniconda3\envs\FriTap\Lib\site-packages\friTap\ssl_logger.py", line 87, in init_fritap
    self.pcap_obj =  PCAP(self.pcap_name,SSL_READ,SSL_WRITE,self.full_capture, self.mobile,self.debug)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jared\miniconda3\envs\FriTap\Lib\site-packages\friTap\pcap.py", line 58, in __init__
    self.android_Instance = Android(self.print_debug_infos)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jared\miniconda3\envs\FriTap\Lib\site-packages\friTap\android.py", line 25, in __init__
    self.tcpdump_version = self._get_appropriate_android_tcpdump_version(arch)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jared\miniconda3\envs\FriTap\Lib\site-packages\friTap\android.py", line 70, in _get_appropriate_android_tcpdump_version
    arch = self._get_android_device_arch()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jared\miniconda3\envs\FriTap\Lib\site-packages\friTap\android.py", line 57, in _get_android_device_arch
    frida_usb_json_data = frida.get_usb_device().query_system_parameters()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jared\miniconda3\envs\FriTap\Lib\site-packages\frida\__init__.py", line 137, in get_usb_device
    return get_device_manager().get_usb_device(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jared\miniconda3\envs\FriTap\Lib\site-packages\frida\core.py", line 1229, in get_usb_device
    return self.get_device_matching(lambda d: d.type == "usb", timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jared\miniconda3\envs\FriTap\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jared\miniconda3\envs\FriTap\Lib\site-packages\frida\core.py", line 1252, in get_device_matching
    return Device(self._impl.get_device_matching(lambda d: predicate(Device(d)), raw_timeout))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.InvalidArgumentError: device not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jared\miniconda3\envs\FriTap\Lib\site-packages\friTap\friTap.py", line 144, in main
    exit(2)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jared\miniconda3\envs\FriTap\Scripts\fritap.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jared\miniconda3\envs\FriTap\Lib\site-packages\friTap\friTap.py", line 189, in main
    ssl_log.pcap_cleanup(parsed.full_capture,parsed.mobile,parsed.pcap)
    ^^^^^^^
UnboundLocalError: cannot access local variable 'ssl_log' where it is not associated with a value

**Comment by SinghSek** [comment]
Update: When running frida-ls-devices, either of the devices when connected do not show up. I tried this in both VSCode and Pycharm terminals running miniconda and python 3.11,  I am using a windows 11 device (ROG Zephyrus g16 2024) and the devices are connected via a usbc port (the usbc cable allows for file transfer).

**Comment by monkeywave** [comment]
Hi @SinghSek,

Thank you for providing detailed information about the issue you're facing, as well as the updates regarding your setup. We greatly appreciate the effort you’ve put into debugging this so far.

### Root Cause
From the logs you’ve shared, it seems the root cause of the issue is that friTap is unable to identify the target device. This is evidenced by the `frida.InvalidArgumentError: device not found` error. The `UnboundLocalError` within FriTap occurs as a consequence of this underlying problem, as the device could not be connected to proceed with the logging.

### Suggested Fix
To address this issue, I recommend explicitly specifying the **device ID** using the `-m` parameter when running friTap. This ensures that Frida correctly identifies and connects to the intended device. You can obtain the device ID in one of the following ways:

1. **Using `frida-ls-devices`:**
Run the following command to list available devices:
   ```bash
   $ frida-ls-devices
   Id              Type    Name                   OS        
   --------------  ------  ---------------------  ----------
   local           local   MacBook-Pro-3.local    macOS 15.2
   emulator-5554   usb     Android Emulator 5554  Android 9 
   09011FDD4007DJ  usb     Pixel 5                Android 13
   ```

2. **Using `adb devices`:**
   Alternatively, use ADB to list connected devices:
   ```bash
   $ adb devices
   List of devices attached
   09011FDD4007DJ	device
   emulator-5554	device
   ```


Once you have the device ID, you can run friTap as follows:

   ```bash
fritap -m <device-id> -k keys.log <PID>
# in my case:
fritap -m 09011FDD4007DJ -k keys.log 17346
   ```


If you encounter any additional issues or need further assistance, feel free to reach out :-)


All the best

Daniel

**Comment by SinghSek** [comment]
Thank you for your response, I've tried looking for the device, but it doesn't show up in Frida, I managed to grab the device ID using adb, and did as you said, but I'm still getting the device not found error. I've also noticed my device seems to restart when I run that code. I have a rooted pixel 9 running android 15, could android 15 be the issue?

**Comment by monkeywave** [comment]
Hi @SinghSek ,

Thank you for the update and for trying out the suggestions. I appreciate your patience in troubleshooting this issue :-)

**Could Android 15 Be the Problem?**
While it's possible that Android 15 could introduce some compatibility challenges, I don’t believe it’s the root cause here. friTap has been tested on various devices and configurations, and Android 15 should not inherently block Frida from working.

**Debug Output Review**
After reviewing the debug output again you previously shared, I noticed that the device ID (`-m` option) was being passed to the Frida script, but not to the capture part of friTap. This issue has been addressed in the latest release **1.2.8.2**. I recommend updating to the latest version and ensuring you provide the device ID when running friTap, as follows:
```bash
fritap -m <device-id> -k keys.log -p pcaptest.pcap --full_capture -do -v
```

If the issue persists, you can try running friTap with only the key extraction functionality. This simplifies the operation and can help identify where the problem lies. Use the following command:
```bash
fritap -m <device-id> -k keys.log -do -v
```

This command skips the packet capture and focuses solely on extracting the keys.

Let me know how it goes! If the problem persists, feel free to share the updated logs or any additional details, and I’ll do my best to assist you further :-)

All the best

Daniel

**Comment by SinghSek** [comment]
Thanks for the help! I managed to get it working after downgrading to android 14. I also found that, while the first try had my device ID show up with the frida-ls-devices command, subsequent tries would have that device missing. What worked for me in that case was restarting the adb server in a terminal, so ./adb kill-server and ./adb start-server. After that, I was able to capture traces.

I did find some weird behaviour where, after collecting traces, it would say that fritap was unable to find the socket used, or something along those lines, is that common for other people too?

**Comment by monkeywave** [comment]
Hey @SinghSek,

Great to hear that it’s now working and the information how you resolved this 😊

Regarding your question about the message "[...] friTap was unable to find the socket used [...]," this is expected behavior when running friTap in full capture mode without also providing the `--socket_tracing` option.

Here’s how it works:
- **Without `--socket_tracing`**: friTap generates a full packet capture (`_<provided_name>.pcap`) that includes all network traffic, without filtering for specific sockets.
- **With `--socket_tracing`**: In addition to the full packet capture, friTap attempts to create a reduced `.pcap` file that contains only the traffic for the traced socket. This will have than the provided name.


If you don’t have any further questions, I’ll go ahead and mark this issue as closed. Let me know if there’s anything else I can assist you with!


All the best

Daniel

**Comment by SinghSek** [comment]
Thank you so much for your help! Just to follow up, have you been able to use this tool to decrypt QUIC traffic in wireshark, I find when using the logged keys as the master key file and even setting the SSLKEYLOG environment variable, that wireshark is still unable to decrypt the QUIC traffic using the keys. I have also update wireshark to the newest version

**Comment by monkeywave** [comment]
Hi @SinghSek,

Thank you for your follow-up question!

### QUIC Traffic Decryption with friTap
Yes, friTap is capable of extracting the keys needed to decrypt QUIC traffic in Wireshark. These are the same keys used for TLS 1.3, so in most cases, Wireshark should be able to decrypt the traffic using the logged keys. However, in some scenarios, it might be necessary to hook specific functions using **BytePatterns**.

You can find more information about hooking by BytePatterns in the friTap documentation:  
[Hooking by BytePatterns](https://github.com/fkie-cad/friTap/tree/main?tab=readme-ov-file#hooking-by-byte-patterns)

To identify these BytePatterns, you can use [BoringSecretHunter](https://github.com/monkeywave/BoringSecretHunter), which is specifically designed for this purpose. Additional details are available in the friTap usage guide:  
[friTap USAGE.md](https://github.com/fkie-cad/friTap/blob/main/USAGE.md#hooking-by-byte-patterns)

### Key Extraction Support
friTap supports key extraction for TLS 1.2, TLS 1.3, and, consequently, QUIC for most libraries. If friTap is unable to detect the library in your specific case, feel free to open a new issue, and we’ll be happy to look into it.

### Missing Keys
If you find that some keys are missing (e.g., those required to decrypt QUIC traffic), you’re welcome to create another issue. Before doing so, please ensure that you’ve followed the guidelines outlined here:  
[friTap Troubleshooting](https://github.com/fkie-cad/friTap/tree/main?tab=readme-ov-file#problems)

The guidelines detail the information that should be included in an issue to help us diagnose and resolve the problem effectively.

### Closing This Issue
Since the original question has been addressed, I’ll go ahead and close this issue. However, if you need further assistance with other aspects of friTap or encounter new problems, don’t hesitate to create a new issue—we’re here to help!


All the best

Daniel
